// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card/Card.vue')['default']
    CardSearch: typeof import('./src/components/CardSearch.vue')['default']
    DamageDice: typeof import('./src/components/Dice/DamageDice.vue')['default']
    Dialog: typeof import('./src/components/Dialog/Dialog.vue')['default']
    DropZone: typeof import('./src/components/DropZone/DropZone.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    Img: typeof import('./src/components/Img.vue')['default']
    Prose: typeof import('./src/components/Prose.vue')['default']
    System: typeof import('./src/components/System/System.vue')['default']
  }
}

export { }
